# Käynnistys seuraavasti
# Powershell komentorivi:       ./mvnw --% spring-boot:run -Dspring-boot.run.profiles=prod
# Bash komentorivi:             ./mvnw spring-boot:run -Dspring-boot.run.profiles=prod

# H2 configuration
spring.h2.console.enabled=create
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always